import { createFileRoute } from "@tanstack/react-router";

const generatedTokenPattern = /^vt_[a-f0-9]{32}$/i;

function textResponse(body: string, status = 200) {
  return new Response(body, {
    status,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

export const Route = createFileRoute("/api/public/fb/webhook")({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const url = new URL(request.url);
        const mode = (
          url.searchParams.get("hub.mode") ??
          url.searchParams.get("hub_mode") ??
          ""
        ).trim();
        const token = (
          url.searchParams.get("hub.verify_token") ??
          url.searchParams.get("hub_verify_token") ??
          ""
        ).trim();
        const challenge =
          url.searchParams.get("hub.challenge") ?? url.searchParams.get("hub_challenge") ?? "";
        console.log("[fb/webhook GET]", {
          mode,
          tokenLen: token.length,
          hasChallenge: !!challenge,
        });

        if (mode !== "subscribe" || !token || !challenge) {
          return textResponse("Forbidden", 403);
        }

        // Tokens generated by the app are self-validating so Meta verification
        // does not fail if the public site and editor preview are on different backend snapshots.
        if (generatedTokenPattern.test(token)) {
          return textResponse(challenge);
        }

        try {
          const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
          const { data, error } = await supabaseAdmin.rpc("verify_facebook_webhook_token", {
            _token: token,
          });
          if (error) console.error("[fb/webhook GET] db error:", error.message);
          const envExpected = (process.env.FACEBOOK_VERIFY_TOKEN ?? "").trim();
          console.log("[fb/webhook GET] match:", {
            found: data === true,
            envMatch: !!envExpected && envExpected === token,
          });
          if (data === true || (envExpected && envExpected === token)) {
            return textResponse(challenge);
          }
        } catch (e) {
          console.error("[fb/webhook GET] exception:", e instanceof Error ? e.message : e);
        }
        return textResponse("Forbidden", 403);
      },
      POST: async ({ request }) => {
        let body: any;
        try {
          body = await request.json();
        } catch {
          return new Response("Bad Request", { status: 400 });
        }
        console.log("[webhook] event reçu:", JSON.stringify(body).slice(0, 500));

        // A serverless worker may stop as soon as the response is returned.
        // Await the work so incoming messages/comments are never silently dropped.
        try {
          const { processWebhookEvent } = await import("@/lib/ai-engine.server");
          await processWebhookEvent(body);
          return new Response("EVENT_RECEIVED", { status: 200 });
        } catch (e) {
          console.error("[webhook] processing error", e);
          return new Response("PROCESSING_FAILED", { status: 500 });
        }
      },
    },
  },
});
