/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAutoPostRouteImport } from './routes/_authenticated/auto-post'
import { Route as AuthenticatedCommentsRouteImport } from './routes/_authenticated/comments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscussionsRouteImport } from './routes/_authenticated/discussions'
import { Route as AuthenticatedFacebookRouteImport } from './routes/_authenticated/facebook'
import { Route as AuthenticatedFormationsRouteImport } from './routes/_authenticated/formations'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMiniIaRouteImport } from './routes/_authenticated/mini-ia'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProduitsRouteImport } from './routes/_authenticated/produits'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ApiPublicPromptFileRouteImport } from './routes/api/public/prompt-file'
import { Route as ApiPublicUploadLocalRouteImport } from './routes/api/public/upload-local'
import { Route as ApiPublicFbCallbackRouteImport } from './routes/api/public/fb/callback'
import { Route as ApiPublicFbWebhookRouteImport } from './routes/api/public/fb/webhook'
import { Route as ApiPublicHooksCronRouteImport } from './routes/api/public/hooks/cron'
import { Route as ApiPublicHooksPublishScheduledPostsRouteImport } from './routes/api/public/hooks/publish-scheduled-posts'
import { Route as ApiPublicHooksReplyAllMessagesRouteImport } from './routes/api/public/hooks/reply-all-messages'
import { Route as ApiPublicSupabaseCallbackRouteImport } from './routes/api/public/supabase/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoPostRoute = AuthenticatedAutoPostRouteImport.update({
  id: '/auto-post',
  path: '/auto-post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommentsRoute = AuthenticatedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscussionsRoute =
  AuthenticatedDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacebookRoute = AuthenticatedFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormationsRoute = AuthenticatedFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiniIaRoute = AuthenticatedMiniIaRouteImport.update({
  id: '/mini-ia',
  path: '/mini-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProduitsRoute = AuthenticatedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPromptFileRoute = ApiPublicPromptFileRouteImport.update({
  id: '/api/public/prompt-file',
  path: '/api/public/prompt-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadLocalRoute = ApiPublicUploadLocalRouteImport.update({
  id: '/api/public/upload-local',
  path: '/api/public/upload-local',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbCallbackRoute = ApiPublicFbCallbackRouteImport.update({
  id: '/api/public/fb/callback',
  path: '/api/public/fb/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbWebhookRoute = ApiPublicFbWebhookRouteImport.update({
  id: '/api/public/fb/webhook',
  path: '/api/public/fb/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCronRoute = ApiPublicHooksCronRouteImport.update({
  id: '/api/public/hooks/cron',
  path: '/api/public/hooks/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishScheduledPostsRoute =
  ApiPublicHooksPublishScheduledPostsRouteImport.update({
    id: '/api/public/hooks/publish-scheduled-posts',
    path: '/api/public/hooks/publish-scheduled-posts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReplyAllMessagesRoute =
  ApiPublicHooksReplyAllMessagesRouteImport.update({
    id: '/api/public/hooks/reply-all-messages',
    path: '/api/public/hooks/reply-all-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSupabaseCallbackRoute =
  ApiPublicSupabaseCallbackRouteImport.update({
    id: '/api/public/supabase/callback',
    path: '/api/public/supabase/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/auto-post': typeof AuthenticatedAutoPostRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discussions': typeof AuthenticatedDiscussionsRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mini-ia': typeof AuthenticatedMiniIaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/prompt-file': typeof ApiPublicPromptFileRoute
  '/api/public/upload-local': typeof ApiPublicUploadLocalRoute
  '/api/public/fb/callback': typeof ApiPublicFbCallbackRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/publish-scheduled-posts': typeof ApiPublicHooksPublishScheduledPostsRoute
  '/api/public/hooks/reply-all-messages': typeof ApiPublicHooksReplyAllMessagesRoute
  '/api/public/supabase/callback': typeof ApiPublicSupabaseCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/auto-post': typeof AuthenticatedAutoPostRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discussions': typeof AuthenticatedDiscussionsRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mini-ia': typeof AuthenticatedMiniIaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/produits': typeof AuthenticatedProduitsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/prompt-file': typeof ApiPublicPromptFileRoute
  '/api/public/upload-local': typeof ApiPublicUploadLocalRoute
  '/api/public/fb/callback': typeof ApiPublicFbCallbackRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/publish-scheduled-posts': typeof ApiPublicHooksPublishScheduledPostsRoute
  '/api/public/hooks/reply-all-messages': typeof ApiPublicHooksReplyAllMessagesRoute
  '/api/public/supabase/callback': typeof ApiPublicSupabaseCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/auto-post': typeof AuthenticatedAutoPostRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discussions': typeof AuthenticatedDiscussionsRoute
  '/_authenticated/facebook': typeof AuthenticatedFacebookRoute
  '/_authenticated/formations': typeof AuthenticatedFormationsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/mini-ia': typeof AuthenticatedMiniIaRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/produits': typeof AuthenticatedProduitsRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/prompt-file': typeof ApiPublicPromptFileRoute
  '/api/public/upload-local': typeof ApiPublicUploadLocalRoute
  '/api/public/fb/callback': typeof ApiPublicFbCallbackRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/hooks/cron': typeof ApiPublicHooksCronRoute
  '/api/public/hooks/publish-scheduled-posts': typeof ApiPublicHooksPublishScheduledPostsRoute
  '/api/public/hooks/reply-all-messages': typeof ApiPublicHooksReplyAllMessagesRoute
  '/api/public/supabase/callback': typeof ApiPublicSupabaseCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api-keys'
    | '/auto-post'
    | '/comments'
    | '/dashboard'
    | '/discussions'
    | '/facebook'
    | '/formations'
    | '/messages'
    | '/mini-ia'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/produits'
    | '/prompts'
    | '/settings'
    | '/utilisateurs'
    | '/api/public/img'
    | '/api/public/prompt-file'
    | '/api/public/upload-local'
    | '/api/public/fb/callback'
    | '/api/public/fb/webhook'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/publish-scheduled-posts'
    | '/api/public/hooks/reply-all-messages'
    | '/api/public/supabase/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api-keys'
    | '/auto-post'
    | '/comments'
    | '/dashboard'
    | '/discussions'
    | '/facebook'
    | '/formations'
    | '/messages'
    | '/mini-ia'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/produits'
    | '/prompts'
    | '/settings'
    | '/utilisateurs'
    | '/api/public/img'
    | '/api/public/prompt-file'
    | '/api/public/upload-local'
    | '/api/public/fb/callback'
    | '/api/public/fb/webhook'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/publish-scheduled-posts'
    | '/api/public/hooks/reply-all-messages'
    | '/api/public/supabase/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/api-keys'
    | '/_authenticated/auto-post'
    | '/_authenticated/comments'
    | '/_authenticated/dashboard'
    | '/_authenticated/discussions'
    | '/_authenticated/facebook'
    | '/_authenticated/formations'
    | '/_authenticated/messages'
    | '/_authenticated/mini-ia'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/produits'
    | '/_authenticated/prompts'
    | '/_authenticated/settings'
    | '/_authenticated/utilisateurs'
    | '/api/public/img'
    | '/api/public/prompt-file'
    | '/api/public/upload-local'
    | '/api/public/fb/callback'
    | '/api/public/fb/webhook'
    | '/api/public/hooks/cron'
    | '/api/public/hooks/publish-scheduled-posts'
    | '/api/public/hooks/reply-all-messages'
    | '/api/public/supabase/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicPromptFileRoute: typeof ApiPublicPromptFileRoute
  ApiPublicUploadLocalRoute: typeof ApiPublicUploadLocalRoute
  ApiPublicFbCallbackRoute: typeof ApiPublicFbCallbackRoute
  ApiPublicFbWebhookRoute: typeof ApiPublicFbWebhookRoute
  ApiPublicHooksCronRoute: typeof ApiPublicHooksCronRoute
  ApiPublicHooksPublishScheduledPostsRoute: typeof ApiPublicHooksPublishScheduledPostsRoute
  ApiPublicHooksReplyAllMessagesRoute: typeof ApiPublicHooksReplyAllMessagesRoute
  ApiPublicSupabaseCallbackRoute: typeof ApiPublicSupabaseCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-post': {
      id: '/_authenticated/auto-post'
      path: '/auto-post'
      fullPath: '/auto-post'
      preLoaderRoute: typeof AuthenticatedAutoPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discussions': {
      id: '/_authenticated/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AuthenticatedDiscussionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facebook': {
      id: '/_authenticated/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof AuthenticatedFacebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formations': {
      id: '/_authenticated/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AuthenticatedFormationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mini-ia': {
      id: '/_authenticated/mini-ia'
      path: '/mini-ia'
      fullPath: '/mini-ia'
      preLoaderRoute: typeof AuthenticatedMiniIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produits': {
      id: '/_authenticated/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prompt-file': {
      id: '/api/public/prompt-file'
      path: '/api/public/prompt-file'
      fullPath: '/api/public/prompt-file'
      preLoaderRoute: typeof ApiPublicPromptFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-local': {
      id: '/api/public/upload-local'
      path: '/api/public/upload-local'
      fullPath: '/api/public/upload-local'
      preLoaderRoute: typeof ApiPublicUploadLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb/callback': {
      id: '/api/public/fb/callback'
      path: '/api/public/fb/callback'
      fullPath: '/api/public/fb/callback'
      preLoaderRoute: typeof ApiPublicFbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb/webhook': {
      id: '/api/public/fb/webhook'
      path: '/api/public/fb/webhook'
      fullPath: '/api/public/fb/webhook'
      preLoaderRoute: typeof ApiPublicFbWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron': {
      id: '/api/public/hooks/cron'
      path: '/api/public/hooks/cron'
      fullPath: '/api/public/hooks/cron'
      preLoaderRoute: typeof ApiPublicHooksCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-scheduled-posts': {
      id: '/api/public/hooks/publish-scheduled-posts'
      path: '/api/public/hooks/publish-scheduled-posts'
      fullPath: '/api/public/hooks/publish-scheduled-posts'
      preLoaderRoute: typeof ApiPublicHooksPublishScheduledPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reply-all-messages': {
      id: '/api/public/hooks/reply-all-messages'
      path: '/api/public/hooks/reply-all-messages'
      fullPath: '/api/public/hooks/reply-all-messages'
      preLoaderRoute: typeof ApiPublicHooksReplyAllMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/supabase/callback': {
      id: '/api/public/supabase/callback'
      path: '/api/public/supabase/callback'
      fullPath: '/api/public/supabase/callback'
      preLoaderRoute: typeof ApiPublicSupabaseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedAutoPostRoute: typeof AuthenticatedAutoPostRoute
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscussionsRoute: typeof AuthenticatedDiscussionsRoute
  AuthenticatedFacebookRoute: typeof AuthenticatedFacebookRoute
  AuthenticatedFormationsRoute: typeof AuthenticatedFormationsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMiniIaRoute: typeof AuthenticatedMiniIaRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProduitsRoute: typeof AuthenticatedProduitsRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedAutoPostRoute: AuthenticatedAutoPostRoute,
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscussionsRoute: AuthenticatedDiscussionsRoute,
  AuthenticatedFacebookRoute: AuthenticatedFacebookRoute,
  AuthenticatedFormationsRoute: AuthenticatedFormationsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMiniIaRoute: AuthenticatedMiniIaRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProduitsRoute: AuthenticatedProduitsRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicPromptFileRoute: ApiPublicPromptFileRoute,
  ApiPublicUploadLocalRoute: ApiPublicUploadLocalRoute,
  ApiPublicFbCallbackRoute: ApiPublicFbCallbackRoute,
  ApiPublicFbWebhookRoute: ApiPublicFbWebhookRoute,
  ApiPublicHooksCronRoute: ApiPublicHooksCronRoute,
  ApiPublicHooksPublishScheduledPostsRoute:
    ApiPublicHooksPublishScheduledPostsRoute,
  ApiPublicHooksReplyAllMessagesRoute: ApiPublicHooksReplyAllMessagesRoute,
  ApiPublicSupabaseCallbackRoute: ApiPublicSupabaseCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
